#
# board/renesas/rzv2h-dev/Makefile
#
# Copyright (C) 2022 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../../renesas/rcar-common/gen3-spl.o
else
obj-y	:= imdt-v2h-sbc.o ../../renesas/rcar-common/common.o
endif
